name: cautious-palm-tree # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. Cautious palm tree, be CAUTIOUSS!.

grade: stable
confinement: strict
license: MIT
icon: snap/gui/icon.jpg
title: Cautious Palm Tree

apps:
  test-server:
    command: server.sh
    daemon: simple
    plugs:
      - network
    slots:
      - test-landing

plugs:
  network:
    interface: network

slots:
  test-landing:
    interface: content
    content: cautious-palm-tree
    source: $SNAP
    source-type: local
    read:
      - $SNAP
